import '../../../../core/data/repositories/base_repository.dart';
import '../models/wallet_model.dart';
import '../services/wallet_service.dart';

/// Repository for wallet operations
class WalletRepository extends BaseRepository {
  final WalletService walletService;

  WalletRepository({required this.walletService});

  /// Get all wallets
  Future<List<WalletModel>> getWallets() => walletService.getWallets();

  /// Get wallet by ID
  Future<WalletModel?> getWalletById(String id) =>
      walletService.getWalletById(id);

  /// Create new wallet
  Future<WalletModel> createWallet({
    required String name,
    required WalletType type,
    double balance = 0,
    bool isPrimary = false,
    String? iconName,
    String? colorHex,
  }) {
    final wallet = WalletModel(
      id: '', // Will be generated by Supabase
      userId: userId,
      name: name,
      type: type,
      balance: balance,
      isPrimary: isPrimary,
      iconName: iconName,
      colorHex: colorHex,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
    return walletService.createWallet(wallet);
  }

  /// Update wallet
  Future<WalletModel> updateWallet(WalletModel wallet) =>
      walletService.updateWallet(wallet);

  /// Delete wallet
  Future<void> deleteWallet(String id) => walletService.deleteWallet(id);

  /// Get total balance
  Future<double> getTotalBalance() => walletService.getTotalBalance();

  /// Create initial wallets from questionnaire
  Future<void> createInitialWallets({
    required double belanjaBalance,
    required double tabunganBalance,
    required double daruratBalance,
  }) async {
    await createWallet(
      name: 'Belanja',
      type: WalletType.belanja,
      balance: belanjaBalance,
      isPrimary: true,
      iconName: 'shopping_bag',
      colorHex: '#304AFF',
    );

    await createWallet(
      name: 'Tabungan',
      type: WalletType.tabungan,
      balance: tabunganBalance,
      iconName: 'savings',
      colorHex: '#10B981',
    );

    await createWallet(
      name: 'Dana Darurat',
      type: WalletType.darurat,
      balance: daruratBalance,
      iconName: 'shield',
      colorHex: '#F59E0B',
    );
  }
}
